// Generated by CoffeeScript 1.10.0
(function() {
  var _, assert, task, taskEnv;

  assert = require('assert');

  _ = require('lodash');

  task = require('../index');

  taskEnv = null;

  describe('Simple Runner Implementation', function() {
    before(function() {
      return taskEnv = new task.TaskEnvironment();
    });
    describe('SimpleRunner', function() {
      it('should be able to register a task implementation', function() {
        var taskFn;
        taskFn = function() {};
        taskEnv.implement("test", taskFn);
        return assert.equal(taskEnv.runner.taskImplementations['test'].taskFn, taskFn);
      });
      return it('should be able to unregister a task implementation', function() {
        assert(taskEnv.runner.taskImplementations['test']);
        taskEnv.unimplement("test");
        return assert(!taskEnv.runner.taskImplementations['test']);
      });
    });
    describe('SimpleScheduler', function() {
      return it('should properly subclass the Scheduler class', function() {
        var scheduler;
        scheduler = new task.SimpleScheduler();
        assert(scheduler instanceof task.SimpleScheduler, "runner is derived from a SimpleScheduler object");
        return assert(scheduler instanceof task.Scheduler, "runner is derived from a Scheduler object");
      });
    });
    return describe('SimpleScheduler', function() {
      return it('should properly subclass the Scheduler class', function() {
        var scheduler;
        scheduler = new task.SimpleScheduler();
        assert(scheduler instanceof task.SimpleScheduler, "runner is derived from a SimpleScheduler object");
        return assert(scheduler instanceof task.Scheduler, "runner is derived from a Scheduler object");
      });
    });
  });

}).call(this);

//# sourceMappingURL=simpleRunnerTest.js.map
