// Generated by CoffeeScript 1.10.0
(function() {
  var _, assert, task, taskEnv;

  assert = require('assert');

  _ = require('lodash');

  task = require('../index');

  taskEnv = null;

  describe('Task Library', function() {
    describe('Default Environment', function() {
      it('should have a SimpleRunner for a runner', function() {
        return assert(task.runner instanceof task.SimpleRunner, "default runner is a SimpleRunner");
      });
      return it('should have a SimpleScheduler for a scheduler', function() {
        return assert(task.scheduler instanceof task.SimpleScheduler, "default scheduler is a SimpleScheduler");
      });
    });
    describe('SimpleRunner', function() {
      return it('should properly subclass the Runner class', function() {
        var runner;
        runner = new task.SimpleRunner();
        assert(runner instanceof task.SimpleRunner, "runner is derived from a SimpleRunner object");
        return assert(runner instanceof task.Runner, "runner is derived from a Runner object");
      });
    });
    describe('SimpleScheduler', function() {
      return it('should properly subclass the Scheduler class', function() {
        var scheduler;
        scheduler = new task.SimpleScheduler();
        assert(scheduler instanceof task.SimpleScheduler, "runner is derived from a SimpleScheduler object");
        return assert(scheduler instanceof task.Scheduler, "runner is derived from a Scheduler object");
      });
    });
    describe('SimpleScheduler', function() {
      return it('should properly subclass the Scheduler class', function() {
        var scheduler;
        scheduler = new task.SimpleScheduler();
        assert(scheduler instanceof task.SimpleScheduler, "runner is derived from a SimpleScheduler object");
        return assert(scheduler instanceof task.Scheduler, "runner is derived from a Scheduler object");
      });
    });
    return describe('Non-Default Environment', function() {
      before(function() {
        return taskEnv = new task.TaskEnvironment();
      });
      it('should have a SimpleRunner for a runner', function() {
        assert(taskEnv.runner instanceof task.SimpleRunner, "environment runner is a SimpleRunner");
        return assert(taskEnv.runner !== task.runner, "environment runner is not default runner");
      });
      return it('should have a SimpleScheduler for a scheduler', function() {
        assert(taskEnv.scheduler instanceof task.SimpleScheduler, "default scheduler is a SimpleScheduler");
        return assert(taskEnv.scheduler !== task.scheduler, "environment scheduler is not default scheduler");
      });
    });
  });

}).call(this);

//# sourceMappingURL=taskTest.js.map
